// Dummy data for Insights section. Replace with API data as needed.
export const insights = [
  {
    id: 1,
    category: 'LEARN',
    title: 'AdGent — the first AI agent to manage paid ads',
    description: 'Discover how AdGent transforms paid media management.',
    author: 'Ryze Team',
    date: 'Jan 15, 2025',
  },
  {
    id: 2,
    category: 'LEARN',
    title: 'Account Structure in 2025: Simplify, Don\'t Complicate',
    description: 'The traditional Alpha/Beta account structure is dead. Learn how to restructure for machine learning.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 3,
    category: 'LEARN',
    title: 'Ad Creative for AI Search: Earning Clicks When AI Answers First',
    description: 'Your creative has to work harder when CTRs are down 40-60%.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 4,
    category: 'LEARN',
    title: 'Ads Inside AI Assistants: The New Frontier',
    description: 'Where Google, OpenAI, Anthropic, and Meta are placing ads inside AI.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 5,
    category: 'LEARN',
    title: 'Advertising in AI-Powered Browsers',
    description: 'Arc, Brave Leo, Opera Aria—new browser AI is changing the game.',
    author: 'Ryze Team',
    date: '2025',
    highlight: true,
  },
  {
    id: 6,
    category: 'LEARN',
    title: 'Advertising in ChatGPT: What Marketers Need to Know',
    description: 'OpenAI is exploring ads in ChatGPT. Here\'s what it means for advertisers.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 7,
    category: 'LEARN',
    title: 'Advertising in Claude: Anthropic\'s Approach',
    description: 'Anthropic\'s Claude doesn\'t run ads—yet. What to watch for.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 8,
    category: 'LEARN',
    title: 'Ads in Google AI Overviews: Complete Guide',
    description: 'Google is placing ads in AI Overviews. Here\'s how it works.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 9,
    category: 'LEARN',
    title: 'Advertising in Google Gemini: What\'s Available',
    description: 'Google\'s Gemini AI doesn\'t run direct ads yet, but opportunities are coming.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 10,
    category: 'LEARN',
    title: 'AdGent — the first AI agent to manage paid ads',
    description: 'Discover how AdGent transforms paid media management.',
    author: 'Ryze Team',
    date: 'Jan 15, 2025',
  },
  {
    id: 11,
    category: 'LEARN',
    title: 'Account Structure in 2025: Simplify, Don\'t Complicate',
    description: 'The traditional Alpha/Beta account structure is dead. Learn how to restructure for machine learning.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 12,
    category: 'LEARN',
    title: 'Ad Creative for AI Search: Earning Clicks When AI Answers First',
    description: 'Your creative has to work harder when CTRs are down 40-60%.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 13,
    category: 'LEARN',
    title: 'Ads Inside AI Assistants: The New Frontier',
    description: 'Where Google, OpenAI, Anthropic, and Meta are placing ads inside AI.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 14,
    category: 'LEARN',
    title: 'Advertising in AI-Powered Browsers',
    description: 'Arc, Brave Leo, Opera Aria—new browser AI is changing the game.',
    author: 'Ryze Team',
    date: '2025',
    highlight: true,
  },
  {
    id: 15,
    category: 'LEARN',
    title: 'Advertising in ChatGPT: What Marketers Need to Know',
    description: 'OpenAI is exploring ads in ChatGPT. Here\'s what it means for advertisers.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 16,
    category: 'LEARN',
    title: 'Advertising in Claude: Anthropic\'s Approach',
    description: 'Anthropic\'s Claude doesn\'t run ads—yet. What to watch for.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 17,
    category: 'LEARN',
    title: 'Ads in Google AI Overviews: Complete Guide',
    description: 'Google is placing ads in AI Overviews. Here\'s how it works.',
    author: 'Ryze Team',
    date: '2025',
  },
  {
    id: 18,
    category: 'LEARN',
    title: 'Advertising in Google Gemini: What\'s Available',
    description: 'Google\'s Gemini AI doesn\'t run direct ads yet, but opportunities are coming.',
    author: 'Ryze Team',
    date: '2025',
  },
];
